sudo: false
language: ruby
rvm:
  - 2.0.0
env:
  global:
    - secure: "S7HUUmGyXbUmbK8HIZn6S8tia3NOh+oGsbBEhlazFzTk2c4hLDwWNQr8ydz4LnikMkCvUeIG9NuXKyeQNmscpf//HPt0ML7OJjPh1jtLP+uB2HiEAAz3u1d66Y563EetFcEpSfMRSamupqBbDG29YgJNuzHHy62ZIDvNCqK6C5A="
branches:
  only:
    - source
addons:
  apt:
    packages:
      - ghc
      - haskell-platform
install:
  - bundle install --path _vendor/bundle
cache: bundler
script: bundle exec jekyll build
after_success:
  - ./deploy.sh setup
  - ./deploy.sh deploy
