name: Andrew Ledvina
markdown: redcarpet
safe: false
lsi: false
highlighter: pygments
timezone: America/Los_Angeles
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"
exclude: [deploy.sh, Gemfile, Gemfile.lock, .travis.yml, postgen.rb, chart_gen.rb, table_gen.rb, generate_reading_data.sh, README.md]
collections:
  writings:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "writings"
    values:
      layout: "base"
