name: Andrew Ledvina
markdown: redcarpet
safe: false
lsi: false
highlighter: pygments
timezone: America/Los_Angeles
paginate: 5
paginate_path: "blog/page:num"
exclude: [deploy.sh, Gemfile, Gemfile.lock, .travis.yml, postgen.rb]
