name: Publish to master

on:
  push:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install
      
      - name: Build site
        run: npm run build

      - name: Init deploy repo
        run: |
          mkdir _deploy
          rm -rf _deploy/*
          cd _deploy/
          git init -q
          git checkout --orphan master -q
          git remote add origin "https://rokob:${{ github.token }}@github.com/rokob/rokob.github.com.git"

      - name: Deploy
        env:
          COMMIT: ${{ github.sha }}
        run: |
          cp -r public/* _deploy/
          cd _deploy/
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"
          git add --all .
          git commit -m "generated from ${COMMIT:0:8}" -q
          git push origin master --force -q
